# Generated by Django 4.0.3 on 2022-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_stay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='address',
            field=models.CharField(max_length=400),
        ),
    ]
