# Generated by Django 4.0.3 on 2022-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_alter_stay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stay',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
    ]
