# Generated by Django 4.0.3 on 2022-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_alter_stay_latitude_alter_stay_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stay',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
    ]
