# Generated by Django 4.0.3 on 2022-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stays', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adult', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('pet', models.IntegerField(default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.status')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
